config/routes.rb
Mongologue::Application.routes.draw do

  match 'signin' => 'sessions#new'
  match 'signout' => 'sessions#destroy'
  match 'authorize' => 'sessions#authorize'
  match 'sitemap' => 'posts#sitemap'
  match 'feed' => 'posts#index'

  match '/posts' => redirect('/')
  match '/admin' => 'admin/posts#index'
  match '/clientinfo' => 'users#clientinfo'

  resources :posts do
    member do
      get :expand_comments
      get :collapse_comments
      get :sitemap
    end
    resources :comments
  end

  resources :tags

  resources :sessions do
    member do
      put :authorize
    end
  end

  resources :users do
    member do
      get :clientinfo
    end
  end

  namespace :admin do
    resources :users do
    end
    resources :posts do
      resources :comments
    end
  end

  root :to => "posts#index"

end

app/models/comment.rb
#encoding: utf-8

class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActionView::Helpers
  include ApplicationHelper

  field :pid, type: Integer
  field :name, type: String
  field :url, type: String
  field :ip, type: String
  field :content, type: String
  field :reply, type: String
  field :reply_name, type: String
  field :reply_url, type: String
  validates_length_of :content, :within => 5..600
  validates_length_of :reply, :maximum => 1000
  validates_length_of :name, :maximum => 60
  validates_length_of :url, :maximum => 200
  before_create :assign_pid
  after_create :inc_counter
  after_destroy :dec_counter
  attr_accessible :content
  before_save :render_text
  embedded_in :post, :inverse_of => :comments

  def render_text
     self.content=sanitize(content,:tags =>%w(i b)) # add auto_link later
     self.content=prepare_text(self.content)
     self.reply=prepare_text(self.reply) unless self.reply.nil?
     return true
  end

  def to_param
    pid
  end

  protected

    def inc_counter
      self._parent.inc(:comments_counter,1)
    end

    def dec_counter
      self._parent.inc(:comments_counter,-1)
    end

    def assign_pid
      self.pid ||= Sequence.generate_pid("post#{self._parent.pid}",:comment)
    end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  include ApplicationHelper

  before_filter :authenticate
  before_filter :admin_user

  before_filter :find_post
  before_filter :find_comment, :except => [:create]

  def find_post
    @post = Post.where(:pid => params[:post_id]).first || not_found
  end

  def find_comment
    @comment = @post.comments.where(:pid => params[:id]).first || not_found
  end

  # Handles only replies
  def edit
    @comment.reply = unprepare_text(@comment.reply) unless @comment.reply.nil?
    # @comment.content = unprepare_text(@comment.content)
    respond_to do |format|
      format.js { render 'edit_reply.js.erb' }
      format.html { render 'edit_reply.html.erb' }
    end
  end

  def destroy
    @comment.destroy
    expire_comments(@post)
    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.xml  { head :ok }
      format.js { render 'destroy_comment.js.erb' }
    end
  end

  # Handles only replies
  def update
    @new_comment = Comment.new

    respond_to do |format|

      @comment.reply = params[:comment][:reply]
      if @comment.reply.empty?
        @comment.reply = nil
        @comment.reply_name = nil
        @comment.reply_url = nil
      else
        @comment.reply_name = identity_or_name(current_user)
        @comment.reply_url = current_user.identity
      end
      if @comment.save
        expire_comments(@post)
        format.html { redirect_to( post_path(@post), notice: "Reply updated.") }
        # format.xml  { head :ok }
        format.js   { render 'comments/show_reply.js.erb' }
      else
        format.html { render :template => 'posts/show' }
        # format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
        format.js   { render 'shared/error_messages.js.erb', :locals => { :object => @comment } }
      end
    end
  end

end

app/controllers/comments_controller.rb
#encoding: utf-8
class CommentsController < ApplicationController
  before_filter :find_post
  before_filter :find_comment, :except => [:create]

  def find_post
    @post = Post.where(:pid => params[:post_id]).first || not_found
  end

  def find_comment
    @comment = @post.comments.where(:pid => params[:id]).first || not_found
  end

  def create
    @new_comment = @post.comments.build(params[:comment])
    if signed_in?
      @new_comment.name = identity_or_name(current_user)
      @new_comment.url = current_user.identity
    else
      @new_comment.name = "Anonymous"
    end

    @new_comment.ip = request.remote_ip

    respond_to do |format|
      if @new_comment.save
        expire_post_with_comments(@post)

        format.html { redirect_to post_path(@post) }
        format.js   { render 'create_comment.js.erb'   }
      else
        format.html { render :template => 'posts/show' }
        format.js   { render 'shared/error_messages.js.erb', :locals => { :object => @new_comment } }
      end
    end

  end

  def show
    respond_to do |format|
      format.js { render 'show_reply.js.erb' }
      format.html { redirect_to post_path(@post) }
    end
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="commentbox" id=<%= "c#{comment.pid}"%>>
  <div class="comment">
  <h3><%= comment.url.nil? ? h(comment.name) : link_to(h(comment.name), comment.url) %></h3>
  <p class="commentinfo"><%= comment.created_at %></p>
    <%= comment.content.html_safe %>
    <div class="reply" id=<%= "r#{comment.pid}" %>>
      <%= render :partial => 'comments/reply', :locals => { :comment => comment }  %>
    </div>
  </div>
</div>

app/views/comments/_reply.html.erb
<% unless comment.reply.nil? %>
  <h3><%= comment.reply_url.nil? ?
          h(comment.reply_name) : link_to(h(comment.reply_name), comment.reply_url) %></h3>
  <%= comment.reply.html_safe %>
<% end %>
<% if authorized_admin? %>
<p class="moderatecomment">IP: <%= comment.ip %> |
<%= link_to comment.reply.nil? ? 'Add reply' : 'Edit reply',
            edit_admin_post_comment_path(@post,comment), :remote => true %> |
<%= link_to 'Delete comment',  admin_post_comment_path(@post, comment), :confirm => 'Are you sure?',
                                        :method => :delete, :remote => true %></p>
<% end %>

app/views/comments/create_comment.js.erb
$("<%= escape_javascript(render :partial => 'comment', :locals => { :comment => @new_comment } ) %>").insertBefore("<%= "#lc#{@post.pid}" %>")
$("<%= "#pc#{@post.pid}" %> form")[0].reset()
$('<%= "#showc#{@post.pid}" %>').replaceWith("<%= escape_javascript(link_to "Comments: #{@post.comments_counter.to_i}", collapse_comments_post_path(@post), :remote => true, :id => "showc#{@post.pid}") %>")

app/views/comments/show_reply.js.erb
$('<%= "#r#{@comment.pid}" %>').html("<%= escape_javascript(render :partial => 'comments/reply', :locals => { :comment => @comment }) %>")