config/routes.rb
Mongologue::Application.routes.draw do

  match 'signin' => 'sessions#new'
  match 'signout' => 'sessions#destroy'
  match 'authorize' => 'sessions#authorize'
  match 'sitemap' => 'posts#sitemap'
  match 'feed' => 'posts#index'

  match '/posts' => redirect('/')
  match '/admin' => 'admin/posts#index'
  match '/clientinfo' => 'users#clientinfo'

  resources :posts do
    member do
      get :expand_comments
      get :collapse_comments
      get :sitemap
    end
    resources :comments
  end

  resources :tags

  resources :sessions do
    member do
      put :authorize
    end
  end

  resources :users do
    member do
      get :clientinfo
    end
  end

  namespace :admin do
    resources :users do
    end
    resources :posts do
      resources :comments
    end
  end

  root :to => "posts#index"

end

app/models/post.rb
#encoding: utf-8

class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActionView::Helpers
  include ApplicationHelper


  field :pid, type: Integer
  field :title
  field :content
  field :html_content
  field :tags, type: Array
  field :comments_counter, type: Integer
  field :keywords, type: Array

  validates_presence_of :title
  validates_presence_of :content
  validates_length_of :title, :maximum => 60
  validates_length_of :content, :maximum => 20000
  validates_length_of :tags_as_string, :maximum => 200

  embeds_many :comments, :inverse_of => :post
  index ({   pid: 1 })
  index ({ title: 1})
  index "comments.pid" => 1

  index ({tags: 1})
  index ({keywords: 1})

  index ({created_at: 1})
  index ({updated_at: 1})
  index "comments.created_at" => 1
  index "comments.updated_at" => 1
  before_save :process_tags_and_keywords
  before_save :render_content
  after_save :rebuild_tags
  after_destroy :rebuild_tags
  before_create :assign_pid

#  def cache_key
#    "#{self.class.name}:#{id}:#{updated_at.to_i}:#{comments_counter}"
#  end

  # Old method, now I have Tag model
  def self.all_tags(limit = nil)
    tagcloud = Mongoid.master.collection('tagcloud')
    opts = { :sort => ["value", :desc] }
    opts[:limit] = limit unless limit.nil?
    tagcloud.find({}, opts).to_set
  end

  # OMG Hack!
  def tags=(arg)
    if (arg.is_a? String)
      super arg.split(",")
    else
      super
    end
  end

  def tags_as_string
    tags.join(", ") unless tags.nil?
  end

  def tags_as_string=(arg)
    if (arg.is_a? String)
      self.tags=arg.split(",")
    end
  end

  def to_param
    pid.to_s
  end

  def get_keywords
    sanitize(self.content,:tags =>%w()).downcase.scan(/[0-9a-zа-я]{3,}/).uniq
  end

  def remove_autotags!
    post_autotags = autotags_flat&(self.tags.to_set)
    self.tags = self.tags.to_set.subtract(autotags_flat).to_a
    return post_autotags
  end

  def process_tags_and_keywords
    # Remove leading and trailing spaces from every tag, force tags into downcase
    self.tags.each_with_index do |t, index|
      self.tags[index] = t.strip.downcase
    end

    # Remove duplicated and empty tags if any
    self.tags.delete("")
    self.tags = self.tags.uniq

    # Add autotags
    # Delete any autotags, in case user entered any
    self.remove_autotags!

    # Add tagless first
    if self.tags.empty?
      self.tags << autotags[:tagless][0]
    end

    # Add html-content related tags

    # Add date
    self.tags << autotags[:year][self.created_at.year-2010]
    self.tags << autotags[:month][self.created_at.month-1]
    self.tags << autotags[:mday][self.created_at.mday-1]
    self.tags << autotags[:wday][self.created_at.wday-1]

    # Add html specific

    # Build list of keywords
    # Strip all html tags
    self.keywords=sanitize(self.content,:tags =>%w()).downcase.scan(/[0-9a-zа-я]{3,}/).uniq

    # Post size
    self.tags << case self.content.length
      when 1..140     then autotags[:size][0]
      when 141..999   then autotags[:size][1]
      when 1000..3999 then autotags[:size][2]
      else                 autotags[:size][3]
    end

    self.tags.delete("")
    self.tags.delete(nil)

  end

  def render_content
    self.html_content = prepare_text(self.content)
  end

  # One crappy piece of code. Refactor.
  def self.my_search(s)
    any_flag = false
    if !s.blank?
      terms = s.gsub(/ *, */,',').gsub(/[^!*0-9a-zа-яё ,]+/,'').strip.downcase.split(',')
      my_tags = Tag.only(:id).map(&:id).to_set

      crit = Post.all
      keywords_and = Array.new
      keywords_not = Array.new
      tags_and = Array.new
      tags_not = Array.new

      terms.each do |t|
        is_keyword = false
        is_tag = false
        is_not = false
        is_like = false

        is_not = true if t.start_with?("!")
        if t.end_with?("*")
         is_keyword = true
         is_like = true
        end

        t.gsub!(/[!*]/,'')

        if my_tags.include?(t)
         is_tag = true unless is_keyword
        else
         is_keyword = true
        end

        t= /^#{t}/ if is_like

        if is_keyword
         if is_not
           keywords_not << t
         else
           keywords_and << t
         end
        else
         if is_not
           tags_not << t
         else
           tags_and << t
         end
        end
     end

     if !any_flag
       crit=crit.all_in(:tags => tags_and) unless tags_and.empty?
       crit=crit.all_in(:keywords => keywords_and) unless keywords_and.empty?
     else
       crit=crit.any_in(:tags => tags_and) unless tags_and.empty?
       crit=crit.any_in(:keywords => keywords_and) unless keywords_and.empty?
     end

     crit=crit.not_in(:tags => tags_not) unless tags_not.empty?
     crit=crit.not_in(:keywords => keywords_not) unless keywords_not.empty?
     return crit
    else
     all
    end
  end


## NEW ERA!

  def nearby_posts(winsize)
    pidmod = pid < (winsize/2).round ? ((winsize/2+1).round-pid) : 0
    Post.only(:pid, :title, :created_at).
         where(:pid.lte => pid+(winsize/2).round+pidmod ).
         desc(:created_at).limit(winsize)
  end

  protected

    def assign_pid
      self.pid ||= Sequence.generate_pid(nil,:post)
    end

    def rebuild_tags
      map     = "function() {
      if (!this.tags) {
          return;
      }

      for (index in this.tags) {
          emit(this.tags[index], 1);
      }
      }"

      reduce  = "function(previous, current) {
      var count = 0;

      for (index in current) {
          count += current[index];
      }
      return count;
      }"

      tmpcloud=Post.map_reduce(map, reduce).out(replace: "tagcloud")
      # Force db hit (wtf?)
      tmpcloud.each do |document|
       # p document
      end

      db = Mongoid::Sessions.default
      tagcloud = db[:tagcloud]
      tagcloud.indexes.create(value: -1)
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  include ApplicationHelper
  include PostsHelper
  before_filter :authenticate
  before_filter :admin_user
  before_filter :find_post, :except => [:new, :create, :index]

  def items_per_page
    if request.format.html? or request.format.js?
      return 15
    else
      return 20
    end
  end

  def find_post
    @post = Post.where(:pid => params[:id]).first || not_found
  end

  # GET /posts
  # GET /posts.xml
  def index
    start_post = Post.where(:pid => params[:p]).first || not_found if params[:p]

    # We have new post form embedded into index
    @post=Post.new

    # Ok, fulltext search goes here
    @posts = Post.without(:comments)
    @posts = @posts.my_search(params[:s]) if params[:s]
    @posts = @posts.order_by([:created_at, :desc])
    @posts = @posts.where(:created_at.lte => start_post.created_at) if params[:p]
    @posts_count = @posts.count
    @posts = @posts.limit(items_per_page+1).to_ary

    @next_page_pid = @posts.size!= items_per_page+1 ? nil : @posts.last.pid

    @title = @posts.first.title if @posts.size!=0

    respond_to do |format|
      format.html { expires_in 0.seconds, :public => false if signed_in?;

                   }
      format.js

      format.json { response.headers["Content-Type"] = "application/json; charset=utf-8";
                    expires_in 0.seconds, :public => false;
                    render :json => @posts }
    end
  end


  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      # format.xml  { render :xml => @post }
      # format.js
    end
  end


  def edit

    @post.remove_autotags!
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])
    @post.created_at = Time.now

    respond_to do |format|
      if @post.save
        expire_cloud
        UserMailer.new_post_email('Mike Ivanov <daekrist@gmail.com>',@post).deliver
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        # format.xml  { render :xml => @post, :status => :created, :location => @post }
        format.js { render 'create.js.erb' }
      else
        format.html { render :action => "new" }
        # format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
        format.js { render 'shared/error_messages.js.erb', :locals => { :object => @post } }
      end
    end
  end


  # PUT /admin/posts/1
  # PUT /admin/posts/1.xml
  def update

    respond_to do |format|
      if @post.update_attributes(params[:post])
        expire_post(@post)
        format.html { redirect_back_or root_path }
        # format.xml  { head :ok }
        format.js   { render 'posts/show.js.erb' }
      else
        format.html { render :action => "edit" }
        # format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
        format.js   { render 'shared/error_messages.js.erb', :locals => { :object => @post } }
      end
    end
  end

  # DELETE /admin/posts/1
  # DELETE /admin/posts/1.xml
  def destroy
    @post.destroy
    expire_post_with_comments(@post)
    expire_action :action => :index
    respond_to do |format|
      # format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
      format.js { render 'destroy.js.erb' }
    end
  end


end

app/controllers/posts_controller.rb
#encoding: utf-8
class PostsController < ApplicationController
  include ApplicationHelper
  include SessionsHelper

  before_filter :store_location
  before_filter :get_post, except: [:index, :sitemap]
  skip_before_filter :get_top_posts, only: :show

  # GET /posts
  # GET /posts.xml
  def index
    # We have new post form embedded into index
    @post=Post.new

    start_post = Post.where(:pid => params[:p]).first || not_found if params[:p]

    @posts = Post.without(:comments).desc(:created_at)

    # Ok, fulltext search goes here
    @posts = @posts.my_search(params[:s]) if params[:s]
    @posts = @posts.where(:created_at.lte => start_post.created_at) if params[:p]
    @posts_count = @posts.count
    @posts = @posts.limit(items_per_page+1)

    @next_page_pid = @posts.size!= items_per_page+1 ? nil : @posts.last.pid

    @title = @posts.first.title if @posts.size!=0

    respond_to do |format|
      format.html { render :html => @posts;
                    memc_write
                   }
      format.js
      format.rss  { response.headers["Content-Type"] = "application/xml; charset=utf-8"
                    render :rss => @posts
                    memc_write }

      format.json { response.headers["Content-Type"] = "application/json; charset=utf-8"
                    render :json => @posts
                    memc_write }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @title = @post.title
    @new_comment = Comment.new
    respond_to do |format|
      format.html { render :html => @post;
                    memc_write
                  }

      format.xml
      format.js
    end
  end

  def collapse_comments
    @new_comment = Comment.new
    respond_to do |format|
      format.js
      format.html { redirect_to post_path(@post) }
    end
  end

  def expand_comments
    @new_comment = Comment.new
    respond_to do |format|
      format.js
      format.html { redirect_to post_path(@post) }
    end
  end

  def sitemap
    @posts=Post.order_by([:created_at, :desc]).only(:pid).all
    @tags=Tag.order_by([:value, :desc]).all
    respond_to do |format|
      format.xml  { response.headers["Content-Type"] = "application/xml; charset=utf-8";
                    render 'sitemap';
                    memc_write(3600)
                  }
    end
  end

private

  def items_per_page
    return 15 if request.format.html? or request.format.js?
    20
  end

  def get_post
    @post = Post.where(:pid => params[:id]).first || not_found
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def link_to_edit(post)
    @edtmplt ||= link_to('Edit', edit_admin_post_path(post), :remote => true)
    return @edtmplt.gsub(/\d+/,post.pid.to_s).html_safe
  end

  def link_to_delete(post)
    @deltmplt ||= link_to('Delete', admin_post_path(post), :confirm => 'Are you sure?', :method => :delete,
                                                        :remote => true)
    return @deltmplt.gsub(/\d+/,post.pid.to_s).html_safe
  end

  def link_to_expand_comments(post,counter)
    @extmplt ||=  link_to "Comments: #{counter}", expand_comments_post_path(post),
                          :remote => true, :id => "showc#{post.pid}"
    return @extmplt.gsub(/\/\d+/,"/#{post.pid}").gsub(/c\d+/,"c#{post.pid}").gsub(/: \d+/,": #{counter}").html_safe
  end

  def link_to_collapse_comments(post,counter)
    @cotmplt ||=  link_to "Comments: #{counter}", collapse_comments_post_path(post),
                          :remote => true, :id => "showc#{post.pid}"
    return @cotmplt.gsub(/\/\d+/,"/#{post.pid}").gsub(/c\d+/,"c#{post.pid}").gsub(/: \d+/,": #{counter}").html_safe
  end

  def link_to_post(post)
    @pstmplt ||= link_to(post.title, post)
    return @pstmplt.gsub(/\d+/,post.pid.to_s).gsub(/>.+</,">#{post.title}<").html_safe
  end

  def tags_list(tags_array)
    tlist = String.new
    tags_array.each do |t|
      tlist="#{tlist}, <a href='/?s=#{t}'>#{t}</a>"
    end
    tlist.sub(', ','').html_safe
  end

  def gplus_post(post)
    "<g:plusone size='small' href='#{polymorphic_url(post)}'></g:plusone>".html_safe
  end

end

app/views/posts/_commclientinfo.html.erb
<% cache("#{current_user.identity}") do %>
<% if signed_in? %>
  <p class="commclientinfo">Signed in as <%= link_to identity_or_name(current_user), current_user.identity %> |
                  <%= link_to "Sign out", signout_path %></p>
<% else %>
  <p class="commclientinfo">Not signed in (anonymous) |
     <%= link_to "Sign in", signin_path(:rt => session[:return_to]) %></p>
<% end %>
<% end %>

app/views/posts/_comments.html.erb
<% cache("pc#{@post.pid}@#{authorized_admin?}") do %>
  <% if @post.comments.size > 0 %>
    <% for comment in @post.comments.order_by(:created_at => :asc) %>
      <% unless comment.new_record? %>
        <%= render comment %>
      <% end %>
    <% end %>
  <% end %>
<div id=<%= "lc#{@post.pid}" %>></div>
<% end %>
<%= render :partial => 'posts/commform' %>

app/views/posts/_commform.html.erb
<% maxlength=500 %>
<% cache("pf#{@post.pid}@#{signed_in?}") do %>
<%= form_for [@post, @new_comment], :html => { :id => "fc#{@post.pid}", :class => "commentform" },
                                    :remote => true do |f| %>
  <%= render "shared/error_messages", :object => @new_comment %>
  <p><%= f.text_area :content, :rows => 10, :maxlength => maxlength %></p>
  <p><%= f.submit %> <span id="<%= "cnt#{@post.pid}" %>"></span></p>
<% end %>
<script type="text/javascript">
    $(document).ready(function(){
    $("<%= "#fc#{@post.pid}" %> textarea").maxChar(<%= maxlength %>, {indicator: "<%= "cnt#{@post.pid}" %>"});

   $('textarea').keypress("enter",function(e){
     if (e.ctrlKey == true && ((e.keyCode == 13) || (e.keyCode == 10))) {
       $(this).closest('form').submit();
      }
     });

    setInterval(function () {
      if($("<%= "#fc#{@post.pid}" %> textarea").val().length <= <%= maxlength %>) {
        $("<%= "#fc#{@post.pid}" %> input").removeAttr("disabled");
      } else {
        $("<%= "#fc#{@post.pid}" %> input").attr("disabled", "disabled");
      }
    }, 200);
  });
</script>
<% end %>

app/views/posts/_form.html.erb
<div id="postform">
<%= form_for(@post, :remote => true) do |f| %>
  <%= render "shared/error_messages", :object => @post %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 20 %>
  </div>
  <div class="field">
    <%= f.label "Tags" %><br />
    <%= f.text_field :tags_helper %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <% unless @post.new_record? %>
      <%= link_to "Cancel", @post, :remote => true %>
    <% end %>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<% cache("p#{post.pid}") do %>
  <div class="post">
    <h2><%= link_to_post(post) %></h2>


    <%= post.html_content.html_safe %>
    <div class="postinfo" title="<%= post.created_at %>"><%= post.created_at %><br>
    Tags: <%= tags_list(post.tags) %></div>
  </div>
<% end %>
<div class="postpanel">
<div style="float:left; width:55px; height: 20px; margin: 0 0 0 15px; display:block;"><%= gplus_post(post) %></div>
<% if admin_url? %>
  <div class="postadm">
  | <%= link_to_edit(post) +' | '+ link_to_delete(post) %>
  </div>
<% end %>
<%= render :partial => 'posts/commcounter', :locals => { :post =>post } %>
</div>

app/views/posts/collapse_comments.js.erb
$('<%= "#pc#{@post.pid}" %>').slideUp()
$('<%= "#showc#{@post.pid}" %>').replaceWith("<%= escape_javascript(link_to "Comments: #{@post.comments_counter.to_i}", expand_comments_post_path(@post), :remote => true, :id => "showc#{@post.pid}" ) %>")

app/views/posts/create.js.erb
$("#new_post")[0].reset()
$("#newpostbox").slideUp()
var postscounter = parseInt($("#postscounter").text())+1
$("#postscounter").text(postscounter)
$('<div id=<%= "pc#{@post.pid}" %> style="display:none;"></div>').insertAfter("#firstpost")
$("<%= escape_javascript(render :partial => 'post', :locals => { :post => @post }) %>").insertAfter("#firstpost")
$("#tagscloud").html("<%= escape_javascript(tags_cloud.html_safe) %>")

app/views/posts/edit.js.erb
$('<%= "#p#{@post.pid}" %>').html("<%= escape_javascript(render('form')) %>")

app/views/posts/expand_comments.js.erb
$('<%= "#pc#{@post.pid}" %>').hide().html("<%= escape_javascript(render('posts/comments')) %>").slideDown()
$('<%= "#showc#{@post.pid}" %>').replaceWith("<%= escape_javascript(link_to "Comments: #{@post.comments_counter.to_i}", collapse_comments_post_path(@post), :remote => true, :id => "showc#{@post.pid}") %>")

app/views/posts/index.html.erb
<div id="posts">
  <div id="firstpost"></div>
  <% @posts.each do |post| %>
    <% if post.pid == @next_page_pid %>
      <% break %>
    <% end %>
    <div id=<%= "p#{post.pid}" %> class="postbox">
    <%= render :partial => '/posts/post', :locals => {:post => post } %>
    </div>
    <div id=<%= "pc#{post.pid}" %> style="display: none;" class="postcomments" ></div>
  <% end %>
</div>
<div id="paginator" class="button" >
<% unless @next_page_pid.nil? %>
  <%= "<a href='?p=#{@next_page_pid}'#{'&s='+params[:s] if params[:s]}'>NEXT PAGE &rarr;</a>".html_safe %>
<% else %>
  <%= link_to_function "&uarr; UP &uarr;".html_safe, "$( 'html, body' ).animate( { scrollTop: 0 }, 0 );" %>
<% end %>
</div>

app/views/posts/new.js.erb
$("#new_post").remove()
$("<div id='new_post' class='postbox'></div>").insertAfter('#firstpost')
$("#new_post").hide().html("<%= escape_javascript(render :partial => 'form') %>").slideDown()
$("#newpostlink").replaceWith("<%= escape_javascript(
                  link_to_function "CANCEL",
"$('#new_post').slideUp();\
 $('#newpostlink').replaceWith('#{link_to 'NEW POST', new_post_path,
                                   :id => "newpostlink", :remote => true }')", :id=>"newpostlink") %>")

app/views/posts/show.html.erb
<div id=<%= "p#{@post.pid}" %> class="postbox">
  <%= render @post %>
</div>
<div id=<%= "pc#{@post.pid}" %> class="postcomments">
  <%= render :partial => 'posts/comments' %>
</div>

app/views/posts/show.js.erb
$('<%= "#p#{@post.pid}" %>').hide("slide", { direction: "left" }, (function(){
var changebutton = 0;
if ($('<%= "#pc#{@post.pid}" %>').css("display") == "none") {
	changebutton = 1;
 }
$('<%= "#p#{@post.pid}" %>').html("<%= escape_javascript(
                                              render :partial => 'posts/post', :locals => { :post => @post }) %>")
$('<%= "#p#{@post.pid}" %>').show("slide", { direction: "right" })

if (changebutton == 1) {
	$('<%= "#showc#{@post.pid}" %>').replaceWith("<%= escape_javascript(link_to "Comments: #{@post.comments_counter.to_i}", expand_comments_post_path(@post), :remote => true, :id => "showc#{@post.pid}") %>")
}
<% if (controller.action_name == "update") || (controller.action_name == "create") %>
  $("#tagscloud p").html("<%= escape_javascript(tags_cloud.html_safe) %>")
<% end %>
}));

app/views/posts/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<% cache('sitemap') do %>
<% @posts.each do |post| %>
<url><loc><%= post_url(post) %></loc></url>
<% end %>
<% @tags.each do |tag| %>
<url><loc><%= root_url+"q=#{tag.id}" %></loc></url>
<% end %>
<% end %>
</urlset>